//
//  CameraViewModel.swift
//  AirLens
//
//  Camera-based prediction with triple verification (PRD AC-2)
//

import Foundation
import UIKit
import Combine

@MainActor
class CameraViewModel: ObservableObject {
    // MARK: - Published Properties
    @Published var selectedImage: UIImage?
    @Published var isProcessing = false
    @Published var prediction: PredictionResult?
    @Published var predictionHistory: [PredictionResult] = []
    @Published var error: Error?
    @Published var processingProgress: Double = 0

    // MARK: - Private Properties
    private let mlService = MLService.shared
    private let fusionService = FusionService.shared
    private let maxHistoryCount = 50 // PRD specification

    init() {
        loadHistory()
    }

    // MARK: - Public Methods

    /// Select and store image
    func selectImage(_ image: UIImage) {
        self.selectedImage = image
        self.prediction = nil
    }

    /// Process image and generate prediction (PRD AC-2: <10s end-to-end)
    func processImage(_ image: UIImage) async {
        let startTime = Date()
        isProcessing = true
        error = nil
        processingProgress = 0

        do {
            // Step 1: Capture frames simulation (in production, use live capture)
            processingProgress = 0.1
            let frames = try await captureFrames(from: image)

            // Step 2: Extract features (PRD: quality scoring + top 15)
            processingProgress = 0.3
            let features = try await mlService.extractFeatures(from: frames)

            // Step 3: Quality assessment
            processingProgress = 0.4
            let topFeatures = selectTopFeatures(features, count: 15)

            // Step 4: ML Inference (PRD: <2s)
            processingProgress = 0.6
            let cameraPM25 = try await mlService.predict(frameFeatures: topFeatures)
            let cameraConfidence = calculateCameraConfidence(features: topFeatures)

            // Step 5: Get location and nearby stations
            processingProgress = 0.7
            let location = LocationService.shared.currentLocation ??
                CLLocationCoordinate2D(latitude: 37.5665, longitude: 126.9780)

            // Mock nearby stations
            let nearbyStations = await getNearbyStations(location: location)

            // Step 6: Triple verification fusion
            processingProgress = 0.9
            let result = await fusionService.fusePredictions(
                cameraPrediction: cameraPM25,
                cameraConfidence: cameraConfidence,
                nearbyStations: nearbyStations,
                satelliteAOD: nil, // Would fetch from service
                location: location
            )

            // Step 7: Store result
            var resultWithImage = result
            resultWithImage.imageData = image.jpegData(compressionQuality: 0.5)

            self.prediction = resultWithImage
            addToHistory(resultWithImage)

            processingProgress = 1.0

            let processingTime = Date().timeIntervalSince(startTime)
            print("✅ Processing completed in \(String(format: "%.2f", processingTime))s")

        } catch {
            self.error = error
            print("❌ Processing failed: \(error)")
        }

        isProcessing = false
    }

    /// Share prediction result
    func sharePrediction() -> String {
        guard let pred = prediction else { return "" }

        return """
        📸 AirLens AI Prediction

        PM2.5: \(pred.formattedPM25) μg/m³
        Category: \(pred.pm25Category.emoji) \(pred.pm25Category.label)
        Confidence: \(pred.confidencePercentage)

        \(pred.pm25Category.description)

        Generated by AirLens - On-device AI air quality prediction
        """
    }

    // MARK: - History Management

    func loadHistory() {
        if let data = UserDefaults.standard.data(forKey: "prediction_history"),
           let history = try? JSONDecoder().decode([PredictionResult].self, from: data) {
            self.predictionHistory = history
        }
    }

    private func addToHistory(_ result: PredictionResult) {
        predictionHistory.insert(result, at: 0)

        // Keep only most recent maxHistoryCount
        if predictionHistory.count > maxHistoryCount {
            predictionHistory = Array(predictionHistory.prefix(maxHistoryCount))
        }

        saveHistory()
    }

    private func saveHistory() {
        if let data = try? JSONEncoder().encode(predictionHistory) {
            UserDefaults.standard.set(data, forKey: "prediction_history")
        }
    }

    // MARK: - Helper Methods

    private func captureFrames(from image: UIImage) async throws -> [UIImage] {
        // In production, this would capture ~30 frames over ~3s
        // For now, simulate with variations of the same image
        return [image]
    }

    private func selectTopFeatures(_ features: [FrameFeature], count: Int) -> [FrameFeature] {
        return features
            .sorted { $0.quality > $1.quality }
            .prefix(count)
            .map { $0 }
    }

    private func calculateCameraConfidence(features: [FrameFeature]) -> Double {
        guard !features.isEmpty else { return 0 }

        let avgQuality = features.map { $0.quality }.reduce(0, +) / Double(features.count)
        let countFactor = min(Double(features.count) / 15.0, 1.0)

        return (avgQuality * 0.7) + (countFactor * 0.3)
    }

    private func getNearbyStations(location: CLLocationCoordinate2D) async -> [Station] {
        // Mock nearby stations
        return [
            Station(
                id: "nearby_1",
                name: "Nearby Station 1",
                latitude: location.latitude + 0.01,
                longitude: location.longitude + 0.01,
                country: "Local",
                pm25: Double.random(in: 10...60),
                pm10: nil,
                aqi: nil,
                updatedAt: Date(),
                no2: nil,
                o3: nil,
                so2: nil,
                co: nil,
                source: "Local",
                credibility: 0.9
            )
        ]
    }
}
